# Generated by Django 6.0.2 on 2026-02-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correlation_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("event_type", models.CharField(default="NEW_INTAKE", max_length=50)),
                ("status", models.CharField(default="READY", max_length=20)),
                (
                    "matrix_room_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "webui_session_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latest_summary", models.TextField(blank=True, null=True)),
                ("next_actions", models.TextField(blank=True, null=True)),
                (
                    "requester_first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requester_last_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "requester_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("intake_id", models.IntegerField(blank=True, null=True)),
                ("structured_output", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
